/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fasa.LojaVirtual.presentation.desktop;

import br.edu.fasa.LojaVirtual.presentation.ServiceLocator;
import br.edu.fasa.LojaVirtual.presentation.frmLojaVirtual;

/**
 *
 * @author petronio
 */
public class frmPrincipal extends javax.swing.JFrame {

    ServiceLocator locator = new ServiceLocator() ;

    public ServiceLocator getServiceLocator() {
        return locator;
    }
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuCadastros = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mnuNovaVenda = new javax.swing.JMenuItem();
        mnuListagemVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuSistema.setText("Sistema");
        jMenuBar1.add(mnuSistema);

        mnuCadastros.setText("Cadastros");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuClientes);

        mnuProdutos.setText("Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuProdutos);

        jMenuBar1.add(mnuCadastros);

        mnuVendas.setText("Vendas");

        mnuNovaVenda.setText("Nova Venda");
        mnuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaVendaActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuNovaVenda);

        mnuListagemVendas.setText("Listagem Vendas");
        mnuListagemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListagemVendasActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuListagemVendas);

        jMenuBar1.add(mnuVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        frmClientes clientes = new frmClientes(getServiceLocator());
        this.add(clientes);

        clientes.setEnabled(true);
        clientes.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        frmProdutos produtos = new frmProdutos(getServiceLocator());
        this.add(produtos);

        produtos.setEnabled(true);
        produtos.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaVendaActionPerformed
        frmNovaVenda venda = new frmNovaVenda(getServiceLocator());
        this.add(venda);

        venda.setEnabled(true);
        venda.setVisible(true);
    }//GEN-LAST:event_mnuNovaVendaActionPerformed

    private void mnuListagemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListagemVendasActionPerformed
        frmVendas venda = new frmVendas(getServiceLocator());
        this.add(venda);

        venda.setEnabled(true);
        venda.setVisible(true);
    }//GEN-LAST:event_mnuListagemVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuListagemVendas;
    private javax.swing.JMenuItem mnuNovaVenda;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenu mnuVendas;
    // End of variables declaration//GEN-END:variables
}
